# Generated by Django 3.2.4 on 2021-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='rank',
            field=models.ImageField(upload_to='media'),
        ),
    ]
